### ISSUE TITLE
Functions as children?

### ISSUE THREAD

**Issue by armand1m** [jamen/h2spec#10]
Hey, this repo seems a really nice idea to build since we've got a lot of libraries building virtual dom's in their way and establish a spec around this would make the ecosystem more compatible and less error prone when switching virtual dom engines. Thanks for starting this.

I've saw in the readme that:

4. `children` must be a `node`, _primitive value_, or an array of either.

 - _primitive value_ is a Boolean, Number, String, null, or undefined (specified by ECMAScript)

But actually, when working with React, Preact or Inferno, or any other Virtual DOMs more established, we can see that there is an existing pattern to run a function as a children.

http://reactpatterns.com/#function-as-children

And, as most of pattern, we have people with their point of view saying that this is an anti-pattern:

http://americanexpress.io/faccs-are-an-antipattern/

Well, knowing this, I thought it was a good idea to start this issue to discuss whether `children` could be a function as well, or if a `function` can be considered as a _primitive value_ 
.

**Comment by armand1m** [comment]
Maybe the function assigned to the children should be called and return always a `node`, _primitive value_, or an array of either?

Maybe if there is a need to use a function as a children, this function should be declared as a IIFE?

**Comment by semibran** [comment]
hi, thanks for starting this issue. Good to see some input on this:raised_hands:

There's really no reason to use anything but an IIFE if you wanted especially complex rendering logic under `children` - ultimately it's about the same amount of work going behind the scenes, just pushing a bit more type-checking work onto any lib that follows the spec.

so you might as well just use something like this:

```js
h("div", (() => {
  if (foo) {
    return "bar"
  } else {
    return "baz"
  }
})())
```

or, more concisely

```js
h("div", foo ? "bar" : "baz")
```

Obviously that's an extremely simple example, but it retains the basic idea. If there's a more practical use case you know of feel free to chime in.
